### ISSUE TITLE
Does the server work? I cannot open the site.

### ISSUE THREAD

**Issue by PaoloZiani** [alexandersimoes/oec#102]

**Comment by davelandry** [comment]
Server works for me. We pushed an update a few days ago that may have briefly taken it down for a few minutes.

Can you check to see if it is currently working for you now?

**Comment by PaoloZiani** [comment]
Sorry, I checked it after some hours and it worked.
________________________________
Da: Dave Landry<mailto:notifications@github.com>
Inviato: ‎29/‎10/‎2015 15:12
A: alexandersimoes/oec<mailto:oec@noreply.github.com>
Cc: PaoloZiani<mailto:paozia@msn.com>
Oggetto: Re: [oec] Does the server work? I cannot open the site. (#102)

Server works for me. We pushed an update a few days ago that may have briefly taken it down for a few minutes.

Can you check to see if it is currently working for you now?

---

**Comment by davelandry** [comment]
:+1:
