### ISSUE TITLE
Can't show the embed tree map in my project

### ISSUE THREAD

**Issue by premkumar6030** [alexandersimoes/oec#104]
Hi,
I have used iframe for nigeria "/en/visualize/embed/tree_map/hs92/export/nga/all/show/2013/" in my project <iframe src="/en/visualize/embed/tree_map/hs92/export/nga/all/show/2013/" width=930 height=400></iframe>. But it display in black screen. What shall I do, to bring up the embed map on my project.For your reference I have attached the screen short below.

![embed map image](https://cloud.githubusercontent.com/assets/15623525/10901528/1b184ea4-8216-11e5-904f-710a2ca2ee5e.png)

**Comment by alexandersimoes** [comment]
Could you paste in the specific URL you are trying to embed?

**Comment by premkumar6030** [comment]
<start iframe tag src="http://atlas.media.mit.edu/en/visualize/embed/tree_map/hs92/import/ner/all/show/2013/" ></end Iframe tag>. Start Iframe tag and end iframe tag used for iframe tags. Because When I paste here iframe code It will not show up here.

**Comment by premkumar6030** [comment]
How to bring the tree map in my project.
What are the steps to bring.

**Comment by premkumar6030** [comment]
How to use iframe and bring the embed tree map inside html file.

**Comment by davelandry** [comment]
found the bug, had to do with not catching an error when the parent window is not from the same site. @alexandersimoes, can you do a pull on the live site?

**Comment by alexandersimoes** [comment]
Ok it's now live and working for me. @premkumar6030 can you confirm this is working?

**Comment by premkumar6030** [comment]
Hi alexandersimoes,
Thank you, Now its working for me.
