### ISSUE TITLE
Reconciling billions Unspecified (HS9999) exports from South Africa to China? 

### ISSUE THREAD

**Issue by JJH501** [alexandersimoes/oec#107]
Dear OEC team, I have noticed in UN Comtrade's data, China's reported import value from South African products diverges greatly from South Africa's reported export value to China, specifically with regards to the Unspecified products of HS9999. 

For example in 2013, China reported $30 billion worth of Unspecified projects imported from South Africa, but the same figure, reported by South Africa, is only 945 thousand. This discrepancy in Unspecified products between China and South Africa is significant considering the total trade volume between the two countries.

I have not found a convincing explanation anywhere online (some said it was gold, or South African rand, or just differences in HS categories used, etc.) Since OEC's data does not include descrepancy in Unspecified products, I'm curious as to how you team was able to reconcile the two figures?

**Comment by alexandersimoes** [comment]
You'll see in our [data sources](http://atlas.media.mit.edu/en/resources/data/) that for HS data (including hs92, 96, 02 and 07 revisions) we use the [BACI International Trade Database](http://www.cepii.fr/CEPII/en/bdd_modele/presentation.asp?id=1) to rectify the differences you mentioned.
