### ISSUE TITLE
Example API call not working

### ISSUE THREAD

**Issue by allenwlee** [alexandersimoes/oec#123]
http://atlas.media.mit.edu/hs/export/2010/usa/all/show/ as shown on the website here: http://atlas.media.mit.edu/api/

returns a 500 error

**Comment by irenelchang** [comment]
If you add in a classification code, i.e. http://atlas.media.mit.edu/hs92/export/2010/usa/all/show/ the API will work

**Comment by allenwlee** [comment]
@irenelchang great thank you
