### ISSUE TITLE
Download fails for HS6 REV. 1996 (1998 - 2014) Product Trade between Origin and Destination Country by Year (6 digit depth, bilateral)

### ISSUE THREAD

**Issue by finbarrtimbers** [alexandersimoes/oec#142]
I'm sorry if this is the wrong place to report this, but when I click on the link to download the 6 digit bilateral trade data for HS6 REV. 1996, the download stops immediately. I can provide more detail if desired.

**Comment by finbarrtimbers** [comment]
Same problem with the HS6 REV. 2002 data.

**Comment by alexandersimoes** [comment]
Thanks for mentioning this... just reexported the files you mentioned. Should be fixed now!
