### ISSUE TITLE
OEC Website Issues

### ISSUE THREAD

**Issue by yasbasgas** [alexandersimoes/oec#143]
Hi there folks,

I was directed to this section by another github user. I am having issues with navigating the OEC website http://atlas.media.mit.edu/en/ 

I am unable to see data information when I hover with the mouse over a specific point. I have attached an image as an example. On a colleagues Laptop he gets all this wonderful information about a specific box whereas I get nothing. Obviously I'm assuming it is some driver/software issue and I am hoping maybe someone out there has had experience with this?

I'm using a Dell XPS 15 (9550) on Windows 10. 

Any advice/help would be highly appreciated as the OEC website is just such a fantastically presented resource; if only I could tap into it... ;-(

Thanks guys...

![image1](https://cloud.githubusercontent.com/assets/22649052/19135813/6d774ab2-8b5f-11e6-848c-0c3372d04604.JPG)

**Comment by alexandersimoes** [comment]
Which browser are you using? There are some known IE bugs with older version. Try using the most recent update of your browser or more specifically Chrome.

**Comment by alexandersimoes** [comment]
Closing for now...
