### ISSUE TITLE
Visualization isn't showing up for "Where does Honduras export knit sweaters to?"

### ISSUE THREAD

**Issue by dwistocki** [alexandersimoes/oec#147]
I attempted to click the "Where does Honduras export knit sweaters to?" after clicking the "knit sweaters" block in the data visualization for Honduran exports. The visualization does not load but instead only shows "Loading Visualization. Powered by D3 Plus" as shown in the attached screenshot. 

<img width="1280" alt="screen shot 2016-11-30 at 9 53 43 pm" src="https://cloud.githubusercontent.com/assets/8098506/20780238/9401f06a-b747-11e6-9ad9-ddc1d5b8c435.png">

**Comment by alexandersimoes** [comment]
This appears to be working for me, feel free to reopen if you find the error again.

http://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/hnd/show/6110/2014/
