### ISSUE TITLE
"Countries" and "Products" pulls up random country or product--can't access list

### ISSUE THREAD

**Issue by codespleen** [alexandersimoes/oec#151]
There appears to be no way to access a list of countries or a list of products. Clicking the menu option for these pulls up a random country profile or a random product profile. Very frustrating.

**Comment by jspeis** [comment]
At any point you can click on the name of the country (on a country profile) or product (from a product profile) and this will open up a search with some repopulated results.

![screen shot 2016-12-31 at 1 14 02 am](https://cloud.githubusercontent.com/assets/87581/21576244/ab78518c-cef6-11e6-890c-2c79a11e796f.png)
![screen shot 2016-12-31 at 1 13 53 am](https://cloud.githubusercontent.com/assets/87581/21576243/ab758bb4-cef6-11e6-8510-ac4147436994.png)

Also, to just see a list of the countries/products on the site take a look at the rankings pages:
http://atlas.media.mit.edu/en/rankings/country/
http://atlas.media.mit.edu/en/rankings/hs92/

**Comment by codespleen** [comment]
This wasn't intuitive design at all for me. Because the magnifying glass is the same size, color, weight, and style as the headline text and located in an area on the screen/page in which one does not usually look for interface elements, I didn't even see it. It was basically invisible to me.
