### ISSUE TITLE
Costa Rica exports very wrong

### ISSUE THREAD

**Issue by schweini** [alexandersimoes/oec#154]
Hi.

on the Costa Rica page
http://atlas.media.mit.edu/en/profile/country/cri/

it says:

The top export destinations of Costa Rica are Malaysia ($3.4B), the Netherlands ($3.01B), the United States ($2.68B), Mexico ($2.53B) and Hong Kong ($1.55B).

Which is completely wrong. Espeically trade with Malaysia is basically non-existent, so some data must have been linked in a wrong way.

**Comment by alexandersimoes** [comment]
We are not the source of the data. Please see the [data](http://atlas.media.mit.edu/en/resources/data/) page.
