### ISSUE TITLE
API docs point to old hs endpoints

### ISSUE THREAD

**Issue by trout11** [alexandersimoes/oec#159]
When I try to make a call using the API example call, I get a 500 Internal Server Error:

[http://atlas.media.mit.edu/hs/export/2010/usa/all/show/](http://atlas.media.mit.edu/hs/export/2010/usa/all/show/
)

**Comment by alexandersimoes** [comment]
I will edit the API docs but in the meantime the endpoint you are looking for is:

http://atlas.media.mit.edu/hs92/export/2010/usa/all/show/
