### ISSUE TITLE
Wrong data of export and import (Slovakia)

### ISSUE THREAD

**Issue by andrejhamara** [alexandersimoes/oec#164]
Hi there, 

on your webpage there is a mistake in Slovak´s export and import data. 
According to comtrade data (https://comtrade.un.org/data/) Slovakia had a positive trade balance ($2,093,612,795) in 2015. Data for previous years are wrong too. Or am I misunderstanding or forgetting something? Thanks for your answer in advance.

Best regards,
Andrej Hamara

**Comment by alexandersimoes** [comment]
Please take a look at our data sources page, the discrepancy is most likely caused by looking at the CEPII data instead of the raw COMTRADE.
