### ISSUE TITLE
Panama Exports/Imports

### ISSUE THREAD

**Issue by njo333** [alexandersimoes/oec#168]
Your site publishes total value for Panamanian imports and exports that appears to vary widely with the source data you claim (COMTRADE) as well as every other publicly available source that I can find. Could you please provide an explanation?

Thanks.

**Comment by alexandersimoes** [comment]
We use 2 different data sources, one is cleaned by CEPII and often varies quite significantly from the raw COMTRADE -- http://atlas.media.mit.edu/en/resources/data/
