### ISSUE TITLE
Cuba CSV files for trade balance

### ISSUE THREAD

**Issue by smit1483** [alexandersimoes/oec#170]
I am trying to download the trade balance data for Cuba as a CSV file.  I am interested in data between Cuba and all nations.  And, also specifically between Cuba and the US, and Cuba and other islands in the West Indies.  However, the downloaded file only has the headers and no numerical data.  I can download other CSV files on the Cuba page, but not import/export numbers.

![image](https://cloud.githubusercontent.com/assets/29041096/26549119/6cdc1e94-4445-11e7-9727-8cb899c06801.png)

**Comment by alexandersimoes** [comment]
This is definitely a bug, thx for making the issue.

**Comment by smit1483** [comment]
Thanks, Alex,

Can you give me a heads up when it is fixed and also a timeline of how long that might take?

Thanks,

Meghan

**Comment by alexandersimoes** [comment]
Just fixed this and pushed the release, let me know if you find any more bugs 🐞
