### ISSUE TITLE
Add Data Africa Embeds to Profile Pages

### ISSUE THREAD

**Issue by alexandersimoes** [alexandersimoes/oec#173]
The thought here is to add embeds for the 13 [Data Africa](https://dataafrica.io/) countries listed below:

```csv
"name","iso3"
"Burkina Faso","BFA"
"Ethiopia","ETH"
"Ghana","GHA"
"Kenya","KEN"
"Malawi","MWI"
"Mali","MLI"
"Mozambique","MOZ"
"Rwanda","RWA"
"Senegal","SEN"
"Uganda","UGA"
"Zambia","ZMB"
"Nigeria","NGA"
"Tanzania","TZA"
```

**Comment by jspeis** [comment]
updated mapping with url_name for api calls:
```
"name","iso3","geo","url_name"
"Burkina Faso","BFA","040AF00042","burkina-faso"
"Ethiopia","ETH","040AF00079","ethiopia"
"Ghana","GHA","040AF00094","ghana"
"Kenya","KEN","040AF00133","kenya"
"Malawi","MWI","040AF00152","malawi"
"Mali","MLI","040AF00155","mali"
"Mozambique","MOZ","040AF00170","mozambique"
"Rwanda","RWA","040AF00205","rwanda"
"Senegal","SEN","040AF00217","senegal"
"Uganda","UGA","040AF00253","uganda"
"Zambia","ZMB","040AF00270","zambia"
"Nigeria","NGA","040AF00182","nigeria"
"Tanzania","TZA","040AF00257","united-republic-of-tanzania"
```

**Comment by davelandry** [comment]
@alexandersimoes they're not live on the server yet, but here's the URL structure:
`https://dataafrica.io/profile/nigeria/CropsByProduction`

**Comment by alexandersimoes** [comment]
Please also post the accompanying title, text and anchor link similar to this format:

![screen shot 2017-06-22 at 6 27 18 pm](https://user-images.githubusercontent.com/252276/27458719-7386f764-5778-11e7-9a27-8b0d10c180b6.png)

**Comment by jspeis** [comment]
@alexandersimoes here are some example Embed URLs:

https://dataafrica.io/profile/nigeria/CropsByProduction
https://dataafrica.io/profile/nigeria/CropsByHarvest

**Comment by davelandry** [comment]
Section background color: `#dddddd`

# Crops by Production Value
This treemap shows the crops produced in <country> sized by their value of production.

Data Africa is an open-source platform designed to provide information on health, agriculture, climate, and poverty across 13 focus countries in Africa. 

Explore on Data Africa - https://dataafrica.io/
Viz - https://dataafrica.io/profile/nigeria/CropsByProduction


# Crops by Harvested Area
This treemap shows the crops produced in <country> sized by their harvested area in hectares.

Explore on Data Africa - https://dataafrica.io/
Viz - https://dataafrica.io/profile/nigeria/CropsByHarvest

**Comment by alexandersimoes** [comment]
Ok it's live! Take a look here -- http://atlas.media.mit.edu/en/profile/country/nga/

I'll keep the issue open until i get the thumbs up from @davelandry and @jspeis

**Comment by davelandry** [comment]
Two things:
- [ ] looks like you didn't compile the CSS?
- [ ] you didn't put a link in the table of contents!

<img width="1260" alt="screen shot 2017-06-26 at 3 19 22 pm" src="https://user-images.githubusercontent.com/1847581/27556277-ef1a6728-5a82-11e7-958b-c120d80de99c.png">

**Comment by jspeis** [comment]
Looks great, my only question: what do you think about having the link text be something along the lines of "Explore More Data on Nigeria" etc.
