### ISSUE TITLE
country codes

### ISSUE THREAD

**Issue by smit1483** [alexandersimoes/oec#180]
Can you please help me with country codes FDR, NAA, and FIO.  These are not listed in the country code definitions and I do not know what they are.

**Comment by pachamaltese** [comment]
Netherland Antilles and Aruba = NAA
Federal Republic of Germany = FDR
??? = FIO

FDR  is not in use since the reunification (RDA and FDR moved to DEU)

**Comment by alexandersimoes** [comment]
FIO = French Indian Ocean
