### ISSUE TITLE
FIO country code

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/oec#181]
Reported by Meghan Brown

Here is an example for Bermuda:
http://atlas.media.mit.edu/en/visualize/tree_map/sitc/import/bmu/show/all/1971/
 
Downloaded, this data has a section as follows:

|year|country_origin_id|region      |country_origin|hs92_product_id|import_val|import_val_pct|    |
|----|-----------------|------------|--------------|---------------|----------|--------------|----|
|1971|BMU              |West Indies?|XXA           |ALL            |191000    |0.0017        |    |
|1971|BMU              |            |NAA           |ALL            |1719000   |0.016         |    |
|1971|BMU              |            |FDR           |ALL            |2224000   |0             |    |

...

|year|country_origin_id|region|country_origin|hs92_product_id|import_val|import_val_pct|    |
|----|-----------------|------|--------------|---------------|----------|--------------|----|
|1977|BMU              |      |FIO           |ALL            |3000      |0.0000021     |    |
|1975|BRB              |      |FIO           |ALL            |1000      |0.0000045     |    |
|1982|CUB              |      |FIO           |ALL            |1707000   |0.0015        |    |

Where 

Special Areas = XXA
Netherland Antilles and Aruba = NAA
Federal Republic of Germany = FDR

The first refers to special areas (e.g. UN Missions)
The third is not in use since the reunification (GDR and FDR moved to DEU)

I did look for Meghan in the R package (R package https://cran.r-project.org/web/packages/oec/index.html that we wrote and provides a list of countries and products) shows in the country list.

However, FIO is does not appear on  the list, and the list comes from the official countries list of the OEC.

**Comment by alexandersimoes** [comment]
From the Feenstra Documentation (for SITC data from 1962 - 2000)
166380 FR IND O (incl. Comoros, UN uses 161740; incl. Reunion, UN uses 166380; incl. Fr.So.Ant.Tr, UN uses 162600)

Source: http://cid.econ.ucdavis.edu/data/undata/NBER-UN_Data_Documentation_w11040.pdf
