### ISSUE TITLE
Germany is duplicated in the 80's

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/oec#183]
Hi

I did explore this

`countries_api = fromJSON("http://atlas.media.mit.edu/attr/country/")`

and Germany appears twice, we need to work on this and when is fixed I can update the R package

![Uploading Screen Shot 2017-08-12 at 18.12.24.png…]()

**Comment by alexandersimoes** [comment]
I'm fixing this at the visualization level so that we can still show time series of germany back to the earliest we have data for (1962).
