### ISSUE TITLE
The textual import/export values double the amount of actual values

### ISSUE THREAD

**Issue by brssrm** [alexandersimoes/oec#212]
Example: "In 2016 Indonesia exported $380B, making it the 28th largest exporter in the world."

While the actual value is $190B (in the tree map). Seems like some bug is doubling the amount. It is also funny that even this value from product categories does not match the value from export destinations ($141B). Something wrong here.

https://atlas.media.mit.edu/en/profile/country/idn/

**Comment by alexandersimoes** [comment]
Thanks for the heads up on this, this issue has been fixed.
