### ISSUE TITLE
Dead links, aggregation request

### ISSUE THREAD

**Issue by manzikki** [alexandersimoes/oec#214]
On page https://atlas.media.mit.edu/en/resources/about/ the links to your thesis do not work since the macroconnectiosn site has changed its name (to macro).

Hot topic today: Aluminium Import/Export:
https://atlas.media.mit.edu/en/visualize/tree_map/hs92/import/usa/show/7601/2016/ (raw aluminium). It would be nice to have the aggregate HS (I think 4-digit) for all types of aluminium.

**Comment by alexandersimoes** [comment]
Fixed!
