### ISSUE TITLE
Visualization pages won't open

### ISSUE THREAD

**Issue by gmaxje** [alexandersimoes/oec#216]
Visualization pages on Kenya, Burundi, Rwanda, Uganda and Tanzania for many years won't open. Like for instance

https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/ken/show/all/2015/  (2016 does work but older doesn't)
and 

https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/bdi/show/all/2000/

They stay blank when I open them. Some work and some don't. I've tried to open them on another browser or other device and the same happens. I've also disabled all sorts of extensions in my browser and deleted my browser history including cookies but nothing seems to help.

**Comment by alexandersimoes** [comment]
Just fixed, thanks!
