### ISSUE TITLE
Page does not load + funny script+ http not https for seconds then came back to https.

### ISSUE THREAD

**Issue by jawjojomsawar** [alexandersimoes/oec#217]
Links not working on my computer :+1:
https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/sen/all/show/2016/
https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/sen/all/show/2015/
https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/civ/all/show/2016/
https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/civ/all/show/2015/

Also the links about bilateral by product.
The page issued an unverified certificate for seconds then switched to http then came back to "normal" (with a very very slow connexion, then the page refused to open. 
I tried other countries like Netherland and they opened easily. 
That would be great if the website works again or if I can get the data (also unavailable)......!!!!

Thanks a lot,
Cheers!

**Comment by alexandersimoes** [comment]
These are now fixed, thanks!
