### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Shiro90** [alexandersimoes/oec#218]
Hi,

I would like to report that some links are dead. I'm doing a research about bulbs but I still get blank pages.

List
https://atlas.media.mit.edu/en/visualize/geo_map/hs92/export/show/all/0601/2016/
https://atlas.media.mit.edu/en/profile/hs92/0601/
https://atlas.media.mit.edu/en/profile/hs92/060110/
https://atlas.media.mit.edu/en/profile/hs92/060120/

I'm not sure but I did an inspect and I get this Mixed Content: The page at 'https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/show/all/0601/2016/' was loaded over HTTPS, but requested an insecure favicon 'http://atlas.media.mit.edu/favicon.ico/'. This request has been blocked; the content must be served over HTTPS.

**Comment by alexandersimoes** [comment]
These are now fixed, thanks for bringing this up!
