### ISSUE TITLE
Previous years now blank

### ISSUE THREAD

**Issue by eagle964** [alexandersimoes/oec#221]
The links to most years and nations are now dead, for example when inserting United States 1971, only leads to a white dead page, concerning visualizations.

**Comment by alexandersimoes** [comment]
Could you the URL that is broken for you? Or the behavior flow that brought you to the broken page?

This page is working for me (showing US exports in 1971 using SITC classification of products): https://atlas.media.mit.edu/en/visualize/tree_map/sitc/export/usa/all/show/1971/

**Comment by eagle964** [comment]
Oh, yeah it works for me fine now, I believe it was the behavior flow that brought me to the blank page but now its fine, thank you!

**Comment by alexandersimoes** [comment]
Great, glad it's working for you now!
