### ISSUE TITLE
Liechtenstein

### ISSUE THREAD

**Issue by RSPatent** [alexandersimoes/oec#227]
Hi Alex,

I mis the OEC data from this country.

Greetings

Ralf

**Comment by alexandersimoes** [comment]
Switzerland and Liechtenstein report their trade together:

https://comtrade.un.org/ITSY2016VolI.pdf

<img width="701" alt="screen shot 2018-08-13 at 11 39 22 am" src="https://user-images.githubusercontent.com/252276/44042152-8fbca54c-9eed-11e8-944f-c675445c2f8e.png">
