### ISSUE TITLE
Have plan to include the data in Year 2017 and thereafter in the system?

### ISSUE THREAD

**Issue by darlingpretty168** [alexandersimoes/oec#229]
This is a great product and I love it!!! I find the data is until Year 2016. Do you have plan to have more recent data on the platform?
Thanks.

**Comment by alexandersimoes** [comment]
Yes, we do but it's currently not released entirely yet (still 10% of counties have not reported 2017 trade data). Take a look at our staging site here for sneak peak: https://oec.world/en/
