### ISSUE TITLE
SITC visualizations not working in viz builder

### ISSUE THREAD

**Issue by Revoman5** [alexandersimoes/oec#247]
Hello there,

when you try to visualize bilateral trade after the SITC system, "500 Internal Server Error" is shown. With the harmonized system it is working perfectly. I am writing my Master's Thesis at the moment and the OEC is helping me so much! But I need those SITC numbers really badly. I hope you can help me! 

Thank you in advance for the help and for the great website, it is just amazing!

**Comment by Revoman5** [comment]
Update: It seems not just to happen for SITC. When trying to visualize trade between two countries in different classification systems and time periods, the internal server error is popping up.

**Comment by alexandersimoes** [comment]
Example broken URL: https://oec.world/en/visualize/tree_map/sitc/import/can/all/show/2016/

**Comment by alexandersimoes** [comment]
Thanks for pointing this out @Revoman5. This issue is now resolved.
