### ISSUE TITLE
Australian Trade Deficit

### ISSUE THREAD

**Issue by AdamMaroti** [alexandersimoes/oec#61]
Dear OEC team,

According to your data, Australia had export of $249B and import of  $240B in 2012. However, Australia had a trade deficit in 2012. Could you explain me what is the reason of this discrepancy?

Thank you

**Comment by alexandersimoes** [comment]
Thanks for your interest. Have you seen this page - http://atlas.media.mit.edu/about/data/sources/? We are not the original source of the data.
