### ISSUE TITLE
Canada Export & Russia export mistakes

### ISSUE THREAD

**Issue by Poniatenko** [alexandersimoes/oec#67]
You say that Russia exported  weapons on <$200 million in 2012. This is absolutely WRONG!
During last years, Russian export of arms was always $10 billion and up. You can see this even in wikipedia.

Canadian export in 2012. Something is wrong with oil. Just ~1% from total, while official Canadian sources say, that its 17%. 
http://www.capp.ca/library/statistics/basic/Pages/default.aspx
This is for 2013, but, obviously, situation in 2012 was almost the same.

Also, total summ  of Canadian export is wrong. $150 billion are missing. Check data for 2011 and you will see the difference.

**Comment by alexandersimoes** [comment]
Please see the response to #61.

**Comment by Poniatenko** [comment]
So, you do not correct mistakes? Maybe, your sources are proper, but you messed up something?
