### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by Ariaabs** [alexandersimoes/oec#71]
Hi, 

I am trying to download .csv files from your website for my research, and since 3 weeks ago I have a problem with the website. Previously, by clicking on the tab "Explore" and selecting my country and other details (such as Import/export, Year, HS/SITC and etc), I was able to download .csv files easily from the link on the right hand side of the webpage. but since 3 weeks ago, whenever I tried to do that instead of downloading the file, I faced with this prompt:

"Method Not Allowed
The method is not allowed for the requested URL."

can you please help me to find a solution for this problem?

**Comment by davelandry** [comment]
This is probably related to the server switching from http to https last week.

**Comment by Ariaabs** [comment]
Thanks for your response. when do you think I can continue my downloads without any problem? It is really important for me to have a complete data base for my research.
