### ISSUE TITLE
Export Data for Canada

### ISSUE THREAD

**Issue by stokarick** [alexandersimoes/oec#76]
Dear Observatory of Economic Complexity (OEC):

I visited this website to see the main exports of Canada:

https://atlas.media.mit.edu/en/profile/country/can/

If you go there, it lists the top export of Canada as "cars" (17%). If you visit the webpage of Statistics Canada:

http://www.statcan.gc.ca/tables-tableaux/sum-som/l01/cst01/gblec04-eng.htm

it seems Canada's largest export in 2014, in terms of value, was "crude oil and crude bitumen" 17.5% of export value. Passenger cars and trucks represented 9.4% of export value.

Best 

Stephen Tokarick

**Comment by alexandersimoes** [comment]
Thanks for your interest. Have you seen this page - http://atlas.media.mit.edu/about/data/sources/? We are not the original source of the data.

**Comment by stokarick** [comment]
If the source of your data is comtrade then there is a problem somewhere. I looked at the comtrade data, available through the website of the international trade center in Geneva and they show Canada's largest export to be petroleum products. I believe the website is intracen.com<http://intracen.com>. They have a lot of information that you have, plus many additional features.

Sent from my iPhone

On Apr 29, 2015, at 11:42 PM, "Alex Simoes" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your interest. Have you seen this page - http://atlas.media.mit.edu/about/data/sources/? We are not the original source of the data.

�
