### ISSUE TITLE
Switzerland's gold export/import amounts

### ISSUE THREAD

**Issue by mmochalov** [alexandersimoes/oec#81]
According to Atlas media Switzerland's import and export of gold are 20% of total import/export of this country what makes about 40 billions for export and same amount for import. But there are different numbers given by Trademap of International trade center (www.trademap.org): 3,1 billion for export and less than 1 billion for import. 

I'm not sure why this happens, but discrepancy of two sources is pretty significant.

**Comment by alexandersimoes** [comment]
I'm not too familiar with www.trademap.org but it seems the source of their data is the raw comtrade data whereas the OEC is using data cleaned and symeterized by [CEPII](http://www.cepii.fr/CEPII/en/bdd_modele/presentation.asp?id=1). We are not the original source of the data so you may want to contact them with specific questions.

**Comment by mmochalov** [comment]
Hello Alexander, there are 2 more questions regarding the Observatory. - For which year statistics are given ? It seems that it's 2012, right ?- What is the meaning of gross/net switch ? Does it mean values prior/after to custom clearence ? Kind regards,Maxim MochalovResearcher, Institute of economics 08.06.2015, 16:58, "Alex Simoes" <notifications@github.com>:I'm not too familiar with www.trademap.org but it seems the source of their data is the raw comtrade data whereas the OEC is using data cleaned and symeterized by CEPII. We are not the original source of the data so you may want to contact them with specific questions.—Reply to this email directly or view it on GitHub.

**Comment by alexandersimoes** [comment]
Gross = reported exports/imports
Net (exports) = Exports - Imports (showing only values > 0)
Net (imports) = Imports - Exports (showing only values > 0)
