### ISSUE TITLE
Balance of Payments

### ISSUE THREAD

**Issue by chris222** [alexandersimoes/oec#83]
Dear Alexander, 

I just discovered your "Observatory of Economic Complexity". It is an absolutely brilliant and unique application! I totally love the many ways one can display import and export data by country and products. 

What about completing the whole balance of payments information? In other words, what about adding imports & exports of services (tourism etc.) and financial goods (banking etc.) to complete the current account, and capital flows to complete capital account and show the full picture of economic complexity? This would be incredibly marvelous!! :-)) 

Given that you already have the whole GUI interface and database, I'm sure it would be feasible to simply plug in the raw data of services and captial flows in addition to import/export of goods?

**Comment by alexandersimoes** [comment]
Is there an available data source to use? If so the tool is open source and we're always looking for new developers to help us incorporate new features. It is built in a fairly modular fashion so you should be able to add a new dataset by copying most of the current infrastructure and adding onto it. Let me know what your level of commitment could be on this and maybe we could collaborate moving forward.

**Comment by chris222** [comment]
World Bank, IMF, OECD or UN could provide such data, see some links below.

Unfortunately I myself don't have time (nor the skills) to contribute, but
this could surely be worth an additional student project or thesis.
Including services and financial flows would really be a great addition.

For instance you can't understand the development of Greece by just looking
at imports/exports of goods without including tourism and sea transport
services (both of which vital to Greece, and both crashed in 2008).

http://data.worldbank.org/indicator/BN.CAB.XOKA.CD/countries
http://stats.oecd.org/Index.aspx?DataSetCode=MEI_BOP
https://www.imf.org/external/np/sta/bop/bop.htm
http://unctad.org/en/Pages/DIAE/Investment%20and%20Enterprise/FDI_Flows.aspx

cheers,
Chris


2015-06-10 17:11 GMT+02:00 Alex Simoes <notifications@github.com>:

**Comment by alexandersimoes** [comment]
Thanks for sending these sources over. We're also quite low on time/resources but if the opportunity presents itself this would be a font-runner of possible new datasets to include.
