### ISSUE TITLE
Incorrect top import origins in the text

### ISSUE THREAD

**Issue by cmanovit** [alexandersimoes/oec#95]
Pick any country, for example http://atlas.media.mit.edu/en/profile/country/chn/

"The top export destinations of China are the United States ($423B), Hong Kong ($270B), Japan ($163B), Germany ($92.5B) and South Korea ($80.3B). The top import origins are the United States ($423B), Hong Kong ($270B), Japan ($163B), Germany ($92.5B) and South Korea ($80.3B)."

The top import origins simply repeat that of export.

**Comment by alexandersimoes** [comment]
Good catch thx for pointing this out.
